import type { Property } from '../types/Property';

export const MOCK_PROPERTIES: Property[] = [
  {
    _id: 'demo-1',
    title: 'Boys PG near University Road',
    slug: 'boys-pg-university-road',
    price: '6500',
    propertyType: 'pg',
    subType: 'Boys',
    category: 'None',
    area: 'University Road',
    city: 'Rajkot',
    state: 'Gujarat',
    sqft: '—',
    description: 'Clean PG with food available. Ideal for students.',
    badge: '2 Sharing',
    isVerified: true,
    foodAvailable: true,
    acAvailable: false,
    amenities: ['WiFi', 'CCTV', 'Housekeeping'],
    images: ['https://placehold.co/800x500/e5e7eb/111827?text=Ivanta+Demo+PG'],
    contactPhone: '+918460567890',
    whatsappNumber: '+918460567890',
    landmarks: [{ name: 'Saurashtra University', distance: '1.2 km' }],
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'demo-2',
    title: 'Girls PG with AC in Bhaktinagar',
    slug: 'girls-pg-ac-bhaktinagar',
    price: '8500',
    propertyType: 'pg',
    subType: 'Girls',
    category: 'None',
    area: 'Bhaktinagar',
    city: 'Rajkot',
    state: 'Gujarat',
    sqft: '—',
    description: 'Comfortable PG with AC + food option.',
    badge: 'Private',
    isVerified: true,
    foodAvailable: true,
    acAvailable: true,
    amenities: ['AC', 'WiFi', 'Power Backup'],
    images: ['https://placehold.co/800x500/e5e7eb/111827?text=Ivanta+Demo+PG+AC'],
    contactPhone: '+918460567890',
    whatsappNumber: '+918460567890',
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'demo-3',
    title: '2 BHK Flat for Rent in Nana Mava',
    slug: '2bhk-rent-nana-mava',
    price: '15000',
    propertyType: 'rent',
    subType: 'Apartment',
    category: 'Popular Property',
    area: 'Nana Mava',
    city: 'Rajkot',
    state: 'Gujarat',
    beds: ['2'],
    baths: '2',
    sqft: '950 sq.ft.',
    description: 'Well maintained 2 BHK with parking. Family preferred.',
    badge: 'Popular',
    isVerified: true,
    amenities: ['Lift', 'Parking', 'Security'],
    images: ['https://placehold.co/800x500/e5e7eb/111827?text=Ivanta+Demo+2BHK'],
    contactPhone: '+918460567890',
    whatsappNumber: '+918460567890',
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'demo-4',
    title: 'Luxury 3 BHK for Sale near 150ft Ring Road',
    slug: 'luxury-3bhk-150ft',
    priceFrom: '1.25 Cr',
    priceTo: '1.55 Cr',
    price: '',
    propertyType: 'buy',
    subType: 'Apartment',
    category: 'Luxury Property',
    area: '150ft Ring Road',
    city: 'Rajkot',
    state: 'Gujarat',
    beds: ['3'],
    baths: '3',
    sqft: '1650 sq.ft.',
    description: 'Premium society, excellent connectivity, ready to move.',
    badge: 'Luxury',
    isVerified: true,
    amenities: ['Gym', 'Garden', 'Club House'],
    images: ['https://placehold.co/800x500/e5e7eb/111827?text=Ivanta+Demo+Luxury'],
    contactPhone: '+918460567890',
    whatsappNumber: '+918460567890',
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'demo-5',
    title: 'Upcoming Project (Builder) — Near Mavdi',
    slug: 'upcoming-project-mavdi',
    priceFrom: '45 L',
    priceTo: '75 L',
    price: '',
    propertyType: 'buy',
    subType: 'Project',
    category: 'Upcoming Projects',
    area: 'Mavdi',
    city: 'Rajkot',
    state: 'Gujarat',
    sqft: '—',
    description: 'New launch project with flexible payment plan.',
    badge: 'New',
    isVerified: true,
    isNewProject: true,
    amenities: ['Parking', 'Security'],
    images: ['https://placehold.co/800x500/e5e7eb/111827?text=Ivanta+Demo+Project'],
    contactPhone: '+918460567890',
    whatsappNumber: '+918460567890',
    createdAt: new Date().toISOString(),
  },
];

